//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_Clothing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public int VariantId { get; set; }
        public int ProductId { get; set; }
        public string SKU { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public decimal Price { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductVariantStock ProductVariantStock { get; set; }
    }
}
