//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_Clothing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantStock
    {
        public int VariantId { get; set; }
        public int Stock { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
